name: life_jyoti
description: A new Flutter project.
publish_to: 'none'  
 
version: 1.0.1+3

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0
  provider: ^6.0.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.6  
  shared_preferences: ^2.1.0
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar: ^5.0.2
  url_launcher: ^6.1.10
  map_launcher: ^2.5.0+1
  expandable_text: ^2.2.0
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  chips_choice: ^3.0.0
  search_page: ^2.3.0
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

   
  assets:
    - assets/Images/
   